"""added column to comment model

Revision ID: 56210e0e7df6
Revises: de02cb7fa1c1
Create Date: 2021-04-27 18:48:44.057300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56210e0e7df6'
down_revision = 'de02cb7fa1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('thoughts', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'thoughts')
    # ### end Alembic commands ###
